### PR TITLE
Revert "Revert "bullhead: redirect /vendor to /system""

### PR DESCRIPTION
**Pull request by utzcoz**
Hi @pdsouza 

When I build maru os for bullhead, the device hangs on boot phase(Google logo), this patch will fix
this problem without build error(your origin revert says origin commit will cause build error so you revert it).

Thanks.

### CODE REVIEW

**Comment by utzcoz** [comment]
Below document about the relationship between `vendor` partition and Project Treble is copied from [AOSP official website](https://source.android.com/devices/architecture/)

> HIDL separates the vendor implementation (device-specific, lower-level software written by silicon manufacturers) from the Android OS framework via a new vendor interface. Vendors or SOC makers build HALs once and place them in a /vendor partition on the device; the framework, in its own partition, can then be replaced with an over-the-air (OTA) update without recompiling the HALs.

**Comment by pdsouza** [comment]
Thank you for your PR. However, I reverted this commit because `maru_bullhead` uses a separate vendor image--we don't put vendor blobs in /system like LineageOS.

If I apply this PR using vendor blobs generated from [android-prepare-vendor](https://github.com/anestisb/android-prepare-vendor), I get this error when running lunch:

```
build/core/envsetup.mk:264: *** TARGET_COPY_OUT_VENDOR must be set to 'vendor' to use a vendor image.  Stop.
```

**Comment by utzcoz** [comment]
@pdsouza, thanks for your detail explanation. But unfortunately, I tested today again and got the same result. Below this my test steps:

1. Clean the code(`make clean`) and re-sync code from maruos(`repo sync -c -j16`).
2. `. build/envsetup.sh`, `lunch 18`(`maru-bullhead`), and `make -j16`, `flashall all  -w`. But when booting, my device sucks in `Google` log, the same as I have mentioned.
3. Then I re-clean the code(`make clean`) and apply my PR, and  build and flash again(`. build/envsetup.sh`, `lunch 18`(`maru-bullhead`), and `make -j16`, `flashall all  -w`), the device boots correctly, and `lxc-start --name jessie` works fine.

**Comment by pdsouza** [comment]
@utzcoz Thanks for the clear steps.

I think I understand what's going on here. You must be using another vendor tree that does not generate a vendor.img. This means you will flash an empty /vendor partition and the device will get stuck on the Google boot logo because it can't find the necessary vendor binaries in /vendor. This relies on the fact that your device has the latest vendor partition already by flashing the latest stock factory image from Google before flashing your ROM. LineageOS does this to avoid having to deal with the vendor.img.

Maru uses [android-prepare-vendor](https://github.com/anestisb/android-prepare-vendor) to generate the vendor tree, which will *also* create a working vendor.img, so users can flash the /vendor partition as well without having to first flash the latest stock image too.

I suggest that you use [android-prepare-vendor](https://github.com/anestisb/android-prepare-vendor) to generate your vendor tree and try your build again, and everything will work.

For newer devices that support Project Treble, we can avoid generating the vendor.img.

**Comment by utzcoz** [comment]
@pdsouza You're right. Before flashing my built ROM, I flashed Google official factory images. I accept your suggestion,  and it works fine without any changes. Thanks you again for brilliant suggestion. Maybe append this suggestion to `README.md` will avoid other people to encounter the same problem.

**Comment by pdsouza** [comment]
@utzcoz Added a note on this in https://github.com/maruos/android_device_lge_bullhead/commit/64fbaa03dab68b2d0ecd10ab2d2ded87a34bb978. Thanks!

**Pull request closed without merging**
